db.url=jdbc:mysql://127.0.0.1:3306/safety_intelligence?rewriteBatchedStatements=true&useServerPrepStmts=false&cachePrepStmts=true&useLocalSessionState=true&useUnicode=true&characterEncoding=utf8&connectTimeout=10000&socketTimeout=120000
db.user=root
db.password=sptech




